name: Build Cache [using jupyter-book]
on:
  schedule:
    # Execute cache weekly at 3am on Monday
    - cron:  '0 3 * * 1'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.13
          environment-file: environment.yml
          activate-environment: quantecon
      - name: Build HTML
        shell: bash -l {0}
        run: |
          jb build lectures --path-output ./ -W --keep-going
      - name: Upload "_build" folder (cache)
        uses: actions/upload-artifact@v4
        with:
          name: build-cache
          path: _build